#!/bin/python3

##
# @file planet
#
# @brief python script for linux command line usage
#
# @section description_planet Description
# Python script for linux command line usage utilizing doggy.py
# 
# @section libraries_main Libraries/Modules
# - doggy
#   - doggy library for database management
# - arparse library
#   - Library for command line interpretation
# - OS 
#   - Library necessary to get home directory

# imports
import doggy
import argparse
import os

# Global Variables
## Home Directory file location
default_file_directory=os.getenv("HOME")

# set up parser
parser = argparse.ArgumentParser()
parser.add_argument("-i", "--init", action="store_true", default=False, help="Initialize all databases necessary to ~/.planet")
parser.add_argument("-a", "--add", action="store_true", default=False, help="Add recipe to database")
parser.add_argument("-r", "--remove", action="store_true", default=False, help="Delete recipe from database")
parser.add_argument("-g", "--generate", action="store_true", default=False, help="Generate pdf grocery list")
parser.add_argument("-I", "--ingredient", action="store_true", default=False, help="Update ingredient database")
parser.add_argument("-C", "--cuisine", action="store_true", default=False, help="Update cuisine database")


# check args
args = parser.parse_args()

if args.init:
    print("init flag")
if args.add:
    print("add flag")
if args.remove:
    print("remove flag")
if args.generate:
    print("generate flag")
if args.ingredient:
    print("ingredient flag")
if args.cuisine:
    print("cuisine flag")
