name: run-doxy

on: [push, pull_request]

jobs:
    RunDoxy:
      runs-on: ubuntu-latest
      container: python:3.9.7
      steps:
        - uses: mattnotmitt/doxygen-action@v1.9.2
        - name: run-doxy
          run: |
            doxygen docs/Doxygen
