name: run-tests

on: [push, pull_request]

jobs:
    RunAllTests:
      runs-on: ubuntu-latest
      container: python:3.9.7
      steps:
        - uses: actions/checkout@v2
        - name: run-tests
          run: |
            pip install -r requirements.txt
            python -m pytest
